print("select any one choice!")
print("1.list")
print("2.tuple")
choice = int(input("enter your choice:"))
if choice == 1:
    myList = ["virat", "raina", "ashwin", "surya"]
    print("list elements:")
    print(myList)
    name = input("enter the element to be inserted:")
    myList.insert(2, name)
    print("inserting elements:")
    print(myList)
    myList.remove("virat")
    print("removing elements:")
    print(myList)
    myList.sort()
    print("sorting elements:")
    print(myList)
elif choice == 2:
    mytupple1 = ("one", "two", "three")
    mytupple2 = ("four", "four", "five", "six")
    mytupple = mytupple1+mytupple2
    print("merging tuple elements:")
    print(mytupple)
    print("length tuple elements:")
    print(len(mytupple))
    modify = list(mytupple)
    modify.append("seven")
    print("adding tuple elements:")
    print(modify)
    l = list(mytupple)
    l[1] = "krish"
    updated = tuple(l)
    print("updated tuple elements:")
    print(updated)
    i = input("enter the element to be counted:")
    print(mytupple.count(i))
